// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHx8NLHOTPigNhIwKPEGaZcRbIgfwgN5U',
    appId: '1:989401234700:web:b07ce0b86219c84a521d29',
    messagingSenderId: '989401234700',
    projectId: 'orchestraapp-18565',
    authDomain: 'orchestraapp-18565.firebaseapp.com',
    storageBucket: 'orchestraapp-18565.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7SlCae5iGZsJEGwD39gSO8P7g64fau5s',
    appId: '1:989401234700:android:a8992ee4e6fca5bd521d29',
    messagingSenderId: '989401234700',
    projectId: 'orchestraapp-18565',
    storageBucket: 'orchestraapp-18565.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkQtqlRzcafJGiMLgAgraW58W8LhoVX70',
    appId: '1:989401234700:ios:468d3ecf8372db90521d29',
    messagingSenderId: '989401234700',
    projectId: 'orchestraapp-18565',
    storageBucket: 'orchestraapp-18565.appspot.com',
    iosBundleId: 'be.pxl.orchestraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkQtqlRzcafJGiMLgAgraW58W8LhoVX70',
    appId: '1:989401234700:ios:889c3e1458b961eb521d29',
    messagingSenderId: '989401234700',
    projectId: 'orchestraapp-18565',
    storageBucket: 'orchestraapp-18565.appspot.com',
    iosBundleId: 'be.pxl.orchestraApp.RunnerTests',
  );
}
